# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    paths:
      - "src/**"
      - ".github/**"
      - "gradle.properties"
      - "build.gradle"
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle.properties', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Display build number
        run: echo Carpet TIS Addition Build \#$GITHUB_RUN_NUMBER
      - name: Set build number in codes
        run: sed -i "s/build.undefined/build.$GITHUB_RUN_NUMBER/g" src/main/java/me/ivan/ivancarpetaddition/IvanCarpetAdditionServer.java gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/
